name: grad_project_focal
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  video_player: ^2.9.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/black_icons/
    - assets/icons/white_icons/
    - assets/images/

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
         - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
         - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
         - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
         - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
     - family: Tajawal
       fonts:
         - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
         - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
         - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
         - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf